# Generated by Django 2.0.6 on 2018-06-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='option',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option',
            field=models.ManyToManyField(to='assessment.Choice'),
        ),
    ]
