# Generated by Django 2.0.6 on 2018-06-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20180615_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('option', models.ManyToManyField(to='assessment.Choice')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option',
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(to='assessment.Question'),
        ),
    ]
