# Generated by Django 2.0.6 on 2018-06-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_questionrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionrating',
            name='rating',
        ),
    ]
