# Generated by Django 2.0.6 on 2019-01-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=150)),
                ('card_type', models.CharField(blank=True, choices=[('C', 'Content'), ('F', 'Feedback')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('prompt', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('video', models.URLField(blank=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('learning_phase', models.CharField(blank=True, choices=[('A', 'Assess'), ('D', 'Discover'), ('F', 'Familiarize'), ('U', 'Use')], max_length=1)),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('K', 'Korean')], max_length=1)),
                ('quizzes', models.ManyToManyField(blank=True, to='assessment.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='CardRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_sequence', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_responses', models.ManyToManyField(blank=True, to='assessment.QuestionRating')),
                ('rating', models.ManyToManyField(blank=True, to='cards.CardRating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('group_cards', models.ManyToManyField(to='cards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('chinese_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('russian_name', models.CharField(blank=True, max_length=150)),
                ('korean_name', models.CharField(blank=True, max_length=150)),
                ('image_chinese', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image_russian', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image_korean', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'chinese_name', 'russian_name', 'korean_name')},
        ),
        migrations.AddField(
            model_name='card',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Subtopic'),
        ),
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Topic'),
        ),
    ]
