# Generated by Django 2.0.6 on 2018-06-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=150)),
                ('card_type', models.CharField(blank=True, choices=[('C', 'Content'), ('Q', 'Assessment'), ('F', 'Feedback')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('prompt', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('video', models.URLField(blank=True)),
                ('duration', models.FloatField()),
                ('learning_phase', models.CharField(blank=True, choices=[('A', 'Assess'), ('D', 'Discover'), ('F', 'Familiarize'), ('U', 'Use')], max_length=1)),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian')], max_length=1)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Subtopic'),
        ),
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Topic'),
        ),
    ]
