# Generated by Django 2.0.6 on 2018-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reference_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='chinese_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='russian_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
