# Generated by Django 2.0.6 on 2018-06-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180613_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('C', 'Content'), ('F', 'Feedback')], max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='reference_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='russian_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
