# Generated by Django 2.0.6 on 2018-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20180615_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.FloatField(),
        ),
    ]
