# Generated by Django 2.0.6 on 2018-06-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20180615_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'chinese_name', 'russian_name')},
        ),
    ]
