# Generated by Django 2.0.6 on 2018-06-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20180618_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assessment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.Quiz'),
            preserve_default=False,
        ),
    ]
