# Generated by Django 2.0.6 on 2018-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20180618_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='chinese_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='russian_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
